### ISSUE TITLE
How to regenerate results for link prediction on FB15K-237?

### ISSUE THREAD

**Issue by RyanOngAI** [zjunlp/AutoKG#2]
Hi there,

Amazing work! Was wondering if you can provide some code files or jupyter notebooks to regenerate the results for the link prediction task on FB15K-237? I feed your provided prompts into chatgpt but couldn't regenerate your results given the output it provides.

Thank you,

Ryan

**Comment by Wangxh-07** [comment]
Hello, thank you for your interest in our work.

The experiments in this section were conducted in April using the interactive interface provided by the website "https://chat.openai.com/". OPENAI has updated the models used on the website in recent months, which may lead to differences in experimental results. You can refer to the paper "[How is ChatGPT's behavior changing over time?](https://arxiv.org/abs/2307.09009)" to understand the changes in ChatGPT. 

Due to timeliness, the conclusions in this paper are for reference only.

**Comment by RyanOngAI** [comment]
Hey @Wangxh-07 , thanks for the prompt response! Is there a specific prompt format (besides the one you listed) where you encourage ChatGPT to provide the desire response? For some reason, they either don't provide the response or just simply repeat the input?

**Comment by Wangxh-07** [comment]
Regarding the question you've raised, my suggestion is that you can follow my format to construct your prompt (or simply use the provided question). This may be helpful to you, but it could also potentially affect the quality of the model's response to some extent, as the construction of the prompt is crucial.

**Comment by RyanOngAI** [comment]
Okay, I will give that a go, thanks @Wangxh-07 !
